version: '3.5'

services:

  # Frontend server by webpack-dev-server
  sample-app:
    container_name: sample-app
    build:
      # current directory in build
      context: ./front
      dockerfile: ./Dockerfile
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
  # Database server using Mysql
  db-server:
    container_name: db-server
    build:
      # current directory in build
      context: ./db
      dockerfile: ./Dockerfile
    ports:
      - '23306:3306'
  # Backend server by golang
  api-server:
    container_name: api-server
    build:
      # current directory in build
      context: ./backend
      dockerfile: ./Dockerfile
    links:
     # Able to accsess to database server
     # ex:
     # mysql -h db-server -uroot
     - db-server
    volumes:
      - ./backend:/go/src/github.com/budougumi0617/react-golang/backend
      - /go/src/github.com/budougumi0617/react-golang/backend/vendor
    ports:
      - '8888:8080'
