version: '3.5'

services:

  sample-app:
    container_name: sample-app
    build:
      # current directory in build
      context: ./front
      dockerfile: ./Dockerfile
    volumes:
      - './front:/usr/src/app'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
